/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myobot_bridge_myo_Myo */

#ifndef _Included_myobot_bridge_myo_Myo
#define _Included_myobot_bridge_myo_Myo
#ifdef __cplusplus
extern "C" {
#endif
#undef myobot_bridge_myo_Myo_ARM_LEFT
#define myobot_bridge_myo_Myo_ARM_LEFT 0L
#undef myobot_bridge_myo_Myo_ARM_RIGHT
#define myobot_bridge_myo_Myo_ARM_RIGHT 1L
#undef myobot_bridge_myo_Myo_ARM_UNKNOWN
#define myobot_bridge_myo_Myo_ARM_UNKNOWN 2L
/*
 * Class:     myobot_bridge_myo_Myo
 * Method:    __initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_myobot_bridge_myo_Myo__1_1initialize
  (JNIEnv *, jobject);

/*
 * Class:     myobot_bridge_myo_Myo
 * Method:    __runHub
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1runHub
  (JNIEnv *, jobject, jint);

/*
 * Class:     myobot_bridge_myo_Myo
 * Method:    __lock
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_myobot_bridge_myo_Myo__1_1lock
  (JNIEnv *, jobject);

/*
 * Class:     myobot_bridge_myo_Myo
 * Method:    __unlock
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_myobot_bridge_myo_Myo__1_1unlock
  (JNIEnv *, jobject);

/*
 * Class:     myobot_bridge_myo_Myo
 * Method:    __isLocked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_myobot_bridge_myo_Myo__1_1isLocked
  (JNIEnv *, jobject);

/*
 * Class:     myobot_bridge_myo_Myo
 * Method:    __isOnArm
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_myobot_bridge_myo_Myo__1_1isOnArm
  (JNIEnv *, jobject);

/*
 * Class:     myobot_bridge_myo_Myo
 * Method:    __getArm
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_myobot_bridge_myo_Myo__1_1getArm
  (JNIEnv *, jobject);

/*
 * Class:     myobot_bridge_myo_Myo
 * Method:    __updateRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1updateRef
  (JNIEnv *, jobject);

/*
 * Class:     myobot_bridge_myo_Myo
 * Method:    __getOrientation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1getOrientation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
