/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myobot_bridge_myo_Myo */

#ifndef _Included_myobot_bridge_myo_Myo
#define _Included_myobot_bridge_myo_Myo
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __initialize
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1initialize
	(JNIEnv *, jclass);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __lock
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1lock
	(JNIEnv *, jclass);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __unlock
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1unlock
	(JNIEnv *, jclass);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __updateRef
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1updateRef
	(JNIEnv *, jclass);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __getOrientation
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1getOrientation
	(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
