/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myobot_bridge_myo_Myo */

#ifndef _Included_myobot_bridge_myo_Myo
#define _Included_myobot_bridge_myo_Myo
#ifdef __cplusplus
extern "C" {
#endif
#undef myobot_bridge_myo_Myo_UNLOCK_HOLD
#define myobot_bridge_myo_Myo_UNLOCK_HOLD 0L
#undef myobot_bridge_myo_Myo_UNLOCK_TIMED
#define myobot_bridge_myo_Myo_UNLOCK_TIMED 1L
#undef myobot_bridge_myo_Myo_LOCKING_POLICY_NONE
#define myobot_bridge_myo_Myo_LOCKING_POLICY_NONE 0L
#undef myobot_bridge_myo_Myo_LOCKING_POLICY_STANDARD
#define myobot_bridge_myo_Myo_LOCKING_POLICY_STANDARD 1L
#undef myobot_bridge_myo_Myo_VIBRATION_SHORT
#define myobot_bridge_myo_Myo_VIBRATION_SHORT 0L
#undef myobot_bridge_myo_Myo_VIBRATION_MEDIUM
#define myobot_bridge_myo_Myo_VIBRATION_MEDIUM 1L
#undef myobot_bridge_myo_Myo_VIBRATION_LONG
#define myobot_bridge_myo_Myo_VIBRATION_LONG 2L
#undef myobot_bridge_myo_Myo_ARM_LEFT
#define myobot_bridge_myo_Myo_ARM_LEFT 0L
#undef myobot_bridge_myo_Myo_ARM_RIGHT
#define myobot_bridge_myo_Myo_ARM_RIGHT 1L
#undef myobot_bridge_myo_Myo_ARM_UNKNOWN
#define myobot_bridge_myo_Myo_ARM_UNKNOWN 2L
#undef myobot_bridge_myo_Myo_POSE_REST
#define myobot_bridge_myo_Myo_POSE_REST 0L
#undef myobot_bridge_myo_Myo_POSE_FIST
#define myobot_bridge_myo_Myo_POSE_FIST 1L
#undef myobot_bridge_myo_Myo_POSE_SPREADFINGERS
#define myobot_bridge_myo_Myo_POSE_SPREADFINGERS 2L
#undef myobot_bridge_myo_Myo_POSE_WAVEIN
#define myobot_bridge_myo_Myo_POSE_WAVEIN 3L
#undef myobot_bridge_myo_Myo_POSE_WAVEOUT
#define myobot_bridge_myo_Myo_POSE_WAVEOUT 4L
#undef myobot_bridge_myo_Myo_POSE_DOUBLETAP
#define myobot_bridge_myo_Myo_POSE_DOUBLETAP 5L
#undef myobot_bridge_myo_Myo_POSE_UNKNOWN
#define myobot_bridge_myo_Myo_POSE_UNKNOWN 6L
	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __initialize
	* Signature: (Ljava/lang/String;)Z
	*/
	JNIEXPORT jboolean JNICALL Java_myobot_bridge_myo_Myo__1_1initialize
	(JNIEnv *, jobject, jstring);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __runHub
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1runHub
	(JNIEnv *, jobject, jint);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __runHubOnce
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1runHubOnce
	(JNIEnv *, jobject, jint);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __lock
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_myobot_bridge_myo_Myo__1_1lock
	(JNIEnv *, jobject);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __unlock
	* Signature: (I)Z
	*/
	JNIEXPORT jboolean JNICALL Java_myobot_bridge_myo_Myo__1_1unlock
	(JNIEnv *, jobject, jint);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __isLocked
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_myobot_bridge_myo_Myo__1_1isLocked
	(JNIEnv *, jobject);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __setLockingPolicy
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1setLockingPolicy
	(JNIEnv *, jobject, jint);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __vibrate
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1vibrate
	(JNIEnv *, jobject, jint);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __notifyUserAction
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1notifyUserAction
	(JNIEnv *, jobject);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __isOnArm
	* Signature: ()Z
	*/
	JNIEXPORT jboolean JNICALL Java_myobot_bridge_myo_Myo__1_1isOnArm
	(JNIEnv *, jobject);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __getArm
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_myobot_bridge_myo_Myo__1_1getArm
	(JNIEnv *, jobject);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __updateRef
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1updateRef
	(JNIEnv *, jobject);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __getOrientation
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1getOrientation
	(JNIEnv *, jobject);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __getPose
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_myobot_bridge_myo_Myo__1_1getPose
	(JNIEnv *, jobject);

	/*
	* Class:     myobot_bridge_myo_Myo
	* Method:    __cleanup
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_myobot_bridge_myo_Myo__1_1cleanup
	(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
