/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myobot_bridge_Myo */

#ifndef _Included_myobot_bridge_Myo
#define _Included_myobot_bridge_Myo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myobot_bridge_Myo
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myobot_bridge_Myo_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
